export const iconMaps = {
  search: 'ic:baseline-search',
  loading: 'ep:loading',
  check: 'material-symbols:check',
  close: 'material-symbols:close',
  delete: 'material-symbols:delete-outline',
  edit: 'material-symbols:edit-document-outline',
  envelop: 'mdi:envelope-outline',
  female: 'material-symbols:female',
  male: 'material-symbols:male',
  fullscreen: 'material-symbols:fullscreen',
  home: 'ant-design:home-outlined',
  'home-fill': 'ant-design:home-filled',
  link: 'mdi:link-variant',
  linux: 'uil:linux',
  mac: 'icon-park-outline:mac-finder',
  windows: 'teenyicons:windows-outline',
  menu: 'material-symbols:menu-rounded',
  minus: 'ic:baseline-minus',
  plus: 'material-symbols:add',
  setting: 'ant-design:setting-outlined',
  top: 'material-symbols:keyboard-arrow-up-rounded',
  user: 'mdi:user',
  warning: 'mdi:warning-circle-outline',
  zoomin: 'fad:zoomin',
  zoomout: 'fad:zoomout',
}